spring:
  application:
    name: ecommerce-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # ddl-auto: update
      ddl-auto: create-drop
    show-sql: true
      
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html