app.image.folder: 'C:\Users\tragi\OneDrive - famifox\Technique\Project\NashtechEcommerceFullstack\ecommerce-backend\src\main\resources\images'
JWT_SECRET: deri de mouse

spring:
  application:
    name: ecommerce-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      # ddl-auto: create-drop
    show-sql: true
  servlet: 
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html